---
- hosts: myjenkins
  gather_facts: false

  vars:
    add_credentials_content: "{{ lookup('file', '../scripts/add-credentials.groovy')
      | regex_replace('System\\.getenv\\(\"(CREDENTIALS_ID)\"\\)', '\"${\\1}\"')
      | regex_replace('System\\.getenv\\(\"(CREDENTIALS_USER)\"\\)', '\"${\\1}\"')
      | regex_replace('System\\.getenv\\(\"(CREDENTIALS_PASS)\"\\)', '\"${\\1}\"') }}"

    add_aws_credentials_content: "{{ lookup('file', '../scripts/add-aws-credentials.groovy')
      | regex_replace('System\\.getenv\\(\"(AWS_CREDENTIALS_ID)\"\\)', '\"${\\1}\"')
      | regex_replace('System\\.getenv\\(\"(AWS_ACCESS_KEY_ID)\"\\)', '\"${\\1}\"')
      | regex_replace('System\\.getenv\\(\"(AWS_SECRET_ACCESS_KEY)\"\\)', '\"${\\1}\"') }}"

  vars_files:
    - vars/credentials.yml

  tasks:
    - name: Add new global credentials
      jenkins_script:
        script: "{{ add_credentials_content }}"
        args:
          CREDENTIALS_ID: "{{ item.id }}"
          CREDENTIALS_USER: "{{ item.username }}"
          CREDENTIALS_PASS: "{{ item.password }}"
        user: admin
        password: jenkins
      loop: "{{ global_credentials }}"
      no_log: True
      register: script_result
      changed_when: "'Result: 1' in script_result.output"

    - name: Add AWS credentials
      jenkins_script:
        script: "{{ add_aws_credentials_content }}"
        args:
          AWS_CREDENTIALS_ID: "{{ item.id }}"
          AWS_ACCESS_KEY_ID: "{{ item.access_key_id }}"
          AWS_SECRET_ACCESS_KEY: "{{ item.secret_access_key }}"
        user: admin
        password: jenkins
      loop: "{{ aws_credentials }}"
      no_log: True
      register: script_result
      changed_when: "'Result: true' in script_result.output"
